"""Salesforce → Tigerpaw CSV conversion engine.

Pure standard library, no Flask. The design rules (see CONTRACT.md):

1. Never infer types. Every cell is a string and is preserved verbatim except
   for the explicit, *logged* cleanups in :func:`clean_cell`. Leading zeros,
   ``"NA"`` and ``"1.00"`` survive untouched.
2. Deterministic decoding — BOM first, then strict UTF-8, then Windows-1252
   (never latin-1, whose 0x80–0x9F range is control characters and is what
   turns a curly apostrophe into invisible garbage).
3. Every changed cell and every dropped row is reported back so the UI can
   show exactly what happened instead of silently rewriting data.
4. Output stays byte-compatible with v1 where v1 was known-good (UTF-8 BOM,
   CRLF) while the *content* is made ASCII-safe by default, so no downstream
   reader can mis-decode it into mojibake.
"""

from __future__ import annotations

import codecs
import csv
import io
import json
import re
import unicodedata
from dataclasses import asdict, dataclass, field

VERSION = "2.0.0"

# --- Transform rules ---------------------------------------------------------

# Canonical Salesforce report column → Tigerpaw import column.
COLUMN_MAPPING: dict[str, str] = {
    "Product Code": "Part Number",
    "Description": "Description",
    "Quantity": "Quantity",
    "Net Unit Price": "Price",
    "Unit Cost": "Cost",
}
REQUIRED_SOURCE = list(COLUMN_MAPPING)
# Source values dropped; column re-emitted empty so Tigerpaw recomputes it.
DROP_COLUMNS = ["Total Price"]
NEW_COLUMNS = [
    "Type",
    "List Price",
    "Vendor",
    "Vendor Part number",
    "Project Phase",
    "Installation Location",
    "Total Price",
    "UOM",
]
DESIRED_ORDER = [
    "Part Number",
    "Description",
    "Quantity",
    "Price",
    "Cost",
    "Total Price",
    "Type",
    "List Price",
    "UOM",
    "Vendor",
    "Vendor Part number",
    "Project Phase",
    "Installation Location",
]
# Output columns that get currency/thousands-separator cleanup.
NUMERIC_COLUMNS = {"Quantity", "Price", "Cost"}

# Accepted spellings for each canonical source column. Matching is on the
# *normalized* header (see _norm_header) and must be exact — no substring
# fuzz, so "Cost: Cost #" (a record number) can never be mistaken for a cost.
ALIASES: dict[str, tuple[str, ...]] = {
    "Product Code": (
        "product code", "product: product code", "productcode", "part number",
        "part #", "part no", "part no.", "sku", "item code", "product sku",
    ),
    "Description": (
        "description", "product description", "line description",
        "line item description", "product: product description",
        "product: description",
    ),
    "Quantity": ("quantity", "qty", "quantity (qty)"),
    "Net Unit Price": ("net unit price", "unit price", "sales price", "net price", "price"),
    "Unit Cost": ("unit cost", "cost", "product cost", "unit cost (usd)"),
}
_ALIAS_LOOKUP: dict[str, str] = {
    alias: canonical for canonical, aliases in ALIASES.items() for alias in aliases
}
GROUP_ALIASES = ("group: group name", "group name", "group")

# Min alias hits for a row to be accepted as the header row.
HEADER_MIN_MATCHES = 3
HEADER_SCAN_ROWS = 30
MAX_LOG_ENTRIES = 2000  # cap on changes / warnings returned to clients

FOOTER_RE = re.compile(
    r"^(grand\s+)?totals?\b|copyright|all rights reserved|confidential information"
    r"|generated by|salesforce\.com|report generated|^subtotal",
    re.IGNORECASE,
)
TOTALS_RE = re.compile(r"^(grand\s+)?totals?\b", re.IGNORECASE)
NUMBER_RE = re.compile(r"^-?(\d+(\.\d+)?|\.\d+)$")
CURRENCY_CODE_RE = re.compile(r"\b(USD|CAD|EUR|GBP|AUD|MXN|NZD|CHF|JPY)\b", re.IGNORECASE)
CURRENCY_SYMBOLS = "$€£¥"
# "Ã"/"Â"/"â" are the lead bytes of 2- and 3-byte UTF-8 sequences as seen
# through cp1252 or latin-1. A false trigger is harmless: the repair only
# sticks when the bytes form valid UTF-8, which real accented words never do.
MOJIBAKE_MARKERS = ("Ã", "Â", "â")

# Smart punctuation / symbols → plain ASCII. Applied always (these never
# carry meaning a Tigerpaw import needs) and logged as kind "punctuation".
PUNCTUATION_MAP: dict[str, str] = {
    # single quotes / primes
    "‘": "'", "’": "'", "‚": "'", "‛": "'", "′": "'",
    # double quotes
    "“": '"', "”": '"', "„": '"', "‟": '"', "″": '"',
    # hyphens / dashes / minus sign
    "‐": "-", "‑": "-", "‒": "-", "–": "-", "—": "-",
    "―": "-", "−": "-",
    "…": "...",     # ellipsis
    "×": "x",       # multiplication sign
    # exotic spaces -> plain space
    " ": " ", " ": " ", " ": " ", " ": " ", "　": " ",
    # zero-width characters and stray BOMs -> removed
    "​": "", "‌": "", "‍": "", "﻿": "",
    "™": "(TM)", "®": "(R)", "©": "(C)",
    "°": "deg",
    "½": "1/2", "¼": "1/4", "¾": "3/4",
    "µ": "u", "μ": "u",
    "±": "+/-",
    "•": "-", "·": "-",
    "⁄": "/",
}
_PUNCT_RE = re.compile("|".join(re.escape(k) for k in sorted(PUNCTUATION_MAP, key=len, reverse=True)))
# C0/C1 control characters except \t \n \r which are handled separately.
_CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]")
_LINEBREAK_RE = re.compile(r"\r\n|\r|\n")
_MULTISPACE_RE = re.compile(r" {2,}")


# --- Options / result types --------------------------------------------------


def _truthy(v) -> bool:
    if isinstance(v, bool):
        return v
    if v is None:
        return False
    return str(v).strip().lower() in ("1", "true", "yes", "on")


@dataclass
class Options:
    ascii_only: bool = True
    bom: bool = True
    quote_all: bool = False
    keep_extras: bool = True
    group_as_phase: bool = False

    _KEYS = (
        ("asciiOnly", "ascii_only"),
        ("bom", "bom"),
        ("quoteAll", "quote_all"),
        ("keepExtras", "keep_extras"),
        ("groupAsPhase", "group_as_phase"),
    )

    @classmethod
    def from_mapping(cls, src) -> "Options":
        """Build from a dict of camelCase keys; values may be bools or strings."""
        opts = cls()
        if not src:
            return opts
        get = src.get
        for camel, snake in cls._KEYS:
            val = get(camel)
            if val is not None:
                setattr(opts, snake, _truthy(val))
        return opts

    def to_dict(self) -> dict:
        return {camel: getattr(self, snake) for camel, snake in self._KEYS}


@dataclass
class Change:
    row: int
    column: str
    from_: str
    to: str
    kind: str
    kinds: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {"row": self.row, "column": self.column, "from": self.from_,
                "to": self.to, "kind": self.kind, "kinds": self.kinds}


@dataclass
class Warning_:
    row: int | None
    column: str | None
    kind: str
    message: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class SkippedRow:
    index: int      # 0-based data-row index (negative = before the header)
    line: int       # 1-based record number in the source file
    reason: str
    preview: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ParseResult:
    encoding: str
    had_bom: bool
    delimiter: str
    header_row_index: int
    original_columns: list[str]
    rows: list[dict[str, str]]
    skipped: list[SkippedRow]
    warnings: list[Warning_]
    mapping: dict[str, str]         # source header → canonical Salesforce name
    aliases_used: dict[str, str]    # source header → canonical (non-canonical spellings only)
    group_column: str | None
    total_price_column: str | None


@dataclass
class ConvertResult:
    parse: ParseResult
    options: Options
    transformed_columns: list[str]
    transformed_rows: list[dict[str, str]]
    changes: list[Change]
    warnings: list[Warning_]
    mapping_out: dict[str, str]     # source header → Tigerpaw column
    added_columns: list[str]
    dropped_columns: list[str]

    def to_csv(self) -> bytes:
        return build_csv(self.transformed_columns, self.transformed_rows, self.options)

    def summary(self) -> dict:
        return {
            "rows": len(self.transformed_rows),
            "skipped": len(self.parse.skipped),
            "changes": len(self.changes),
            "warnings": len(self.warnings),
            "encoding": self.parse.encoding,
        }

    def summary_json(self) -> str:
        return json.dumps(self.summary(), separators=(",", ":"))


# --- Decoding ----------------------------------------------------------------


def decode_bytes(data: bytes) -> tuple[str, str, bool, list[Warning_]]:
    """Return ``(text, encoding_name, had_bom, warnings)``.

    Order matters: UTF-32 BOMs start with the UTF-16 LE BOM bytes, so they are
    checked first. BOM-less UTF-16 is recognised by NUL density. We never try
    latin-1: it "succeeds" on any bytes and maps 0x80–0x9F (where Windows puts
    curly quotes and dashes) to invisible control characters.
    """
    warnings: list[Warning_] = []
    if data.startswith(codecs.BOM_UTF8):
        return data[len(codecs.BOM_UTF8):].decode("utf-8", errors="replace"), "utf-8-sig", True, warnings
    if data.startswith(codecs.BOM_UTF32_LE) or data.startswith(codecs.BOM_UTF32_BE):
        return data.decode("utf-32", errors="replace"), "utf-32", True, warnings
    if data.startswith(codecs.BOM_UTF16_LE) or data.startswith(codecs.BOM_UTF16_BE):
        return data.decode("utf-16", errors="replace"), "utf-16", True, warnings

    sample = data[:4096]
    if sample and sample.count(b"\x00") / len(sample) > 0.2:
        # Roughly half the bytes are NUL → almost certainly UTF-16 without a BOM.
        odd_nuls = sample[1::2].count(b"\x00")
        even_nuls = sample[0::2].count(b"\x00")
        for enc in (("utf-16-le", "utf-16-be") if odd_nuls >= even_nuls else ("utf-16-be", "utf-16-le")):
            try:
                return data.decode(enc), enc, False, warnings
            except UnicodeDecodeError:
                continue

    try:
        return data.decode("utf-8"), "utf-8", False, warnings
    except UnicodeDecodeError:
        pass
    try:
        return data.decode("cp1252"), "cp1252", False, warnings
    except UnicodeDecodeError:
        pass
    warnings.append(Warning_(None, None, "decode_replaced",
                             "Some bytes were not valid Windows-1252 and were replaced."))
    return data.decode("cp1252", errors="replace"), "cp1252", False, warnings


# --- Header handling ---------------------------------------------------------


def _norm_header(h: str) -> str:
    """Normalize a header cell for alias matching."""
    h = h.replace("﻿", "").strip().strip('"').strip("'").strip()
    h = _MULTISPACE_RE.sub(" ", h.replace("\t", " ").replace("\n", " ").replace("\r", " "))
    return h.lower()


def _clean_header_name(h: str) -> str:
    """Display form of a header: BOM/quotes stripped, whitespace collapsed, case kept."""
    h = h.replace("﻿", "").strip().strip('"').strip("'").strip()
    return _MULTISPACE_RE.sub(" ", h.replace("\t", " ").replace("\n", " ").replace("\r", " "))


def _detect_delimiter(text: str) -> str:
    """Pick the delimiter that produces the best header match in the first rows.

    Sniffing only the first line breaks on exports that carry a title line above
    the header (a lone quoted string has no delimiter at all), so every
    candidate delimiter is tried against the first HEADER_SCAN_ROWS records and
    scored by alias hits; field count on the first non-empty line breaks ties.
    """
    lines = [ln for ln in text.splitlines() if ln.strip()][:HEADER_SCAN_ROWS]
    if not lines:
        return ","
    best_delim, best_key = ",", (-1, -1)
    for delim in (",", ";", "	", "|"):
        try:
            records = list(csv.reader(lines, delimiter=delim))
        except csv.Error:
            continue
        hits = max((len(_header_matches(r)) for r in records), default=0)
        width = len(records[0]) if records else 0
        key = (hits, width)
        if key > best_key:
            best_delim, best_key = delim, key
    return best_delim


def _header_matches(cells: list[str]) -> dict[str, str]:
    """Return {source header → canonical} for the alias hits in a candidate row."""
    found: dict[str, str] = {}
    claimed: set[str] = set()
    for cell in cells:
        canonical = _ALIAS_LOOKUP.get(_norm_header(cell))
        if canonical and canonical not in claimed:
            found[_clean_header_name(cell)] = canonical
            claimed.add(canonical)
    return found


# --- Cell cleanup ------------------------------------------------------------


def _repair_mojibake(s: str) -> str:
    """Undo UTF-8 text that was once mis-read as Windows-1252 (e.g. â€™ → ’)."""
    if not any(m in s for m in MOJIBAKE_MARKERS):
        return s
    # Garbling happens two ways: Windows tools read the bytes as cp1252 (and
    # pass the five undefined bytes through as C1 controls), Java/Linux tools
    # read them as latin-1. Encoding cp1252-first with a latin-1 fallback
    # recovers the original byte string in both cases.
    def _to_byte(ch: str) -> bytes:
        try:
            return ch.encode("cp1252")
        except UnicodeEncodeError:
            if ord(ch) <= 0xFF:  # latin-1 style passthrough (Java/Linux tools)
                return bytes([ord(ch)])
            raise
    try:
        fixed = b"".join(_to_byte(ch) for ch in s).decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return s
    before = sum(1 for ch in s if ord(ch) > 127)
    after = sum(1 for ch in fixed if ord(ch) > 127)
    return fixed if after < before else s


def _strip_accents(s: str) -> str:
    decomposed = unicodedata.normalize("NFKD", s)
    return "".join(ch for ch in decomposed if not unicodedata.combining(ch))


def _clean_number(s: str) -> str | None:
    """Return a plain numeric string, or None if ``s`` isn't recognisably a number."""
    t = s.strip()
    if not t:
        return t
    negative = False
    if t.startswith("(") and t.endswith(")"):
        negative = True
        t = t[1:-1]
    t = CURRENCY_CODE_RE.sub("", t)
    t = "".join(ch for ch in t if ch not in CURRENCY_SYMBOLS)
    t = t.replace(",", "").replace(" ", "")
    if t.startswith("-"):
        negative = not negative
        t = t[1:]
    if t.startswith("+"):
        t = t[1:]
    if not NUMBER_RE.match(t) or t.startswith("-"):
        return None
    return ("-" if negative else "") + t


def clean_cell(value, column: str, options: Options) -> tuple[str, list[str]]:
    """Apply the cleanup pipeline to one cell.

    Returns ``(new_value, kinds)`` where ``kinds`` lists which cleanup steps
    actually changed something, in the order they fired. ``kinds`` may also
    contain the pseudo-kind ``"non_numeric"`` which is a *warning*, not a
    change (the value is left untouched in that case).
    """
    if value is None:
        return "", []
    original = str(value)
    s = original
    kinds: list[str] = []

    repaired = _repair_mojibake(s)
    if repaired != s:
        kinds.append("mojibake")
        s = repaired

    t = _LINEBREAK_RE.sub(" ", s)
    if t != s:
        kinds.append("linebreak")
        s = t
    t = _CONTROL_RE.sub("", s.replace("\t", " "))
    if t != s:
        kinds.append("control")
        s = t

    t = _PUNCT_RE.sub(lambda m: PUNCTUATION_MAP[m.group(0)], s)
    if t != s:
        kinds.append("punctuation")
        s = t

    t = _MULTISPACE_RE.sub(" ", s).strip()
    if t != s:
        kinds.append("whitespace")
        s = t

    if column in NUMERIC_COLUMNS and s:
        num = _clean_number(s)
        if num is None:
            kinds.append("non_numeric")
        elif num != s:
            kinds.append("number")
            s = num

    if options.ascii_only and any(ord(ch) > 127 for ch in s):
        t = _strip_accents(s)
        t = "".join(ch if ord(ch) < 128 else "?" for ch in t)
        if t != s:
            kinds.append("non_ascii")
            s = t

    return s, kinds


def clean_rows(columns: list[str], rows: list[dict], options: Options,
               ) -> tuple[list[dict[str, str]], list[Change], list[Warning_]]:
    """Clean every cell of every row; used by both the file path and the edited path."""
    out_rows: list[dict[str, str]] = []
    changes: list[Change] = []
    warnings: list[Warning_] = []
    for i, row in enumerate(rows):
        new_row: dict[str, str] = {}
        for col in columns:
            raw = row.get(col)
            raw_str = "" if raw is None else str(raw)
            new, kinds = clean_cell(raw_str, col, options)
            if "non_numeric" in kinds:
                kinds.remove("non_numeric")
                warnings.append(Warning_(i, col, "non_numeric",
                                         f"{col} value {raw_str!r} is not a plain number."))
            if kinds and new != raw_str:
                changes.append(Change(i, col, raw_str, new, kinds[0], kinds))
            new_row[col] = new
        if not new_row.get("Part Number", "x"):
            warnings.append(Warning_(i, "Part Number", "empty_part_number", "Part Number is empty."))
        if not new_row.get("Description", "x"):
            warnings.append(Warning_(i, "Description", "empty_description", "Description is empty."))
        out_rows.append(new_row)
    return out_rows, changes, warnings


# --- Parsing -----------------------------------------------------------------


def _row_preview(cells: list[str]) -> str:
    text = " | ".join(c.strip() for c in cells if c.strip())
    return text[:120]


def parse_salesforce_csv(data: bytes) -> ParseResult:
    """Decode, find the header row, and return raw string rows with drop log."""
    text, encoding, had_bom, warnings = decode_bytes(data)
    # Lone CR line endings (old Mac exports) would otherwise confuse the csv
    # module mid-field; embedded CRs get collapsed to spaces later anyway.
    text = re.sub(r"\r(?!\n)", "\n", text)
    if not text.strip():
        raise ValueError("The uploaded CSV file is empty or could not be parsed.")

    delimiter = _detect_delimiter(text)
    reader = csv.reader(io.StringIO(text, newline=""), delimiter=delimiter)
    try:
        records = list(reader)
    except csv.Error as e:
        raise ValueError(f"Could not parse CSV: {e}") from e
    if not records:
        raise ValueError("The uploaded CSV file is empty or could not be parsed.")

    # Header detection: the row (within the first N) with the most alias hits.
    best_idx, best_hits = -1, 0
    for i, cells in enumerate(records[:HEADER_SCAN_ROWS]):
        hits = len(_header_matches(cells))
        if hits > best_hits:
            best_idx, best_hits = i, hits
    if best_hits < HEADER_MIN_MATCHES:
        candidate = records[best_idx] if best_idx >= 0 else next((r for r in records if any(c.strip() for c in r)), [])
        found = set(_header_matches(candidate).values())
        missing = [c for c in REQUIRED_SOURCE if c not in found]
        raise ValueError(f"Missing expected columns in CSV: {', '.join(missing)}")
    header_idx = best_idx
    header_map = _header_matches(records[header_idx])
    missing = [c for c in REQUIRED_SOURCE if c not in header_map.values()]
    if missing:
        raise ValueError(f"Missing expected columns in CSV: {', '.join(missing)}")

    skipped: list[SkippedRow] = []
    for i in range(header_idx):
        if any(c.strip() for c in records[i]):
            skipped.append(SkippedRow(i - header_idx, i + 1, "preamble", _row_preview(records[i])))

    # Build display header names; dedupe with " (2)", " (3)" suffixes.
    raw_headers = [_clean_header_name(h) for h in records[header_idx]]
    headers: list[str] = []
    seen: dict[str, int] = {}
    for pos, h in enumerate(raw_headers):
        name = h or f"Column {pos + 1}"
        if name in seen:
            seen[name] += 1
            warnings.append(Warning_(None, name, "duplicate_header",
                                     f"Duplicate header '{name}' — later copy kept as '{name} ({seen[name]})'."))
            name = f"{name} ({seen[name]})"
        else:
            seen[name] = 1
        headers.append(name)
    ncols = len(headers)

    mapping: dict[str, str] = {}
    aliases_used: dict[str, str] = {}
    claimed: set[str] = set()
    group_column: str | None = None
    total_price_column: str | None = None
    for h in headers:
        norm = _norm_header(h)
        canonical = _ALIAS_LOOKUP.get(norm)
        if canonical and canonical not in claimed:
            mapping[h] = canonical
            claimed.add(canonical)
            if norm != canonical.lower():
                aliases_used[h] = canonical
            continue
        if group_column is None and norm in GROUP_ALIASES:
            group_column = h
        if total_price_column is None and norm == "total price":
            total_price_column = h
    part_header = next(h for h, c in mapping.items() if c == "Product Code")
    desc_header = next(h for h, c in mapping.items() if c == "Description")
    qty_header = next(h for h, c in mapping.items() if c == "Quantity")

    rows: list[dict[str, str]] = []
    seen_blank = False
    for rec_pos in range(header_idx + 1, len(records)):
        cells = records[rec_pos]
        data_idx = rec_pos - header_idx - 1
        line_no = rec_pos + 1
        non_empty = [c for c in cells if c.strip()]

        if not non_empty:
            skipped.append(SkippedRow(data_idx, line_no, "blank", ""))
            seen_blank = True
            continue
        if len(non_empty) == 1 and (FOOTER_RE.search(non_empty[0].strip()) or seen_blank):
            skipped.append(SkippedRow(data_idx, line_no, "footer", _row_preview(cells)))
            continue

        if len(cells) != ncols:
            extra_content = any(c.strip() for c in cells[ncols:])
            if len(cells) < ncols or extra_content:
                warnings.append(Warning_(data_idx, None, "ragged_row",
                                         f"Row has {len(cells)} cells, header has {ncols}; padded/truncated."))
            cells = (cells + [""] * ncols)[:ncols]

        row = dict(zip(headers, cells))
        # Salesforce writes "Grand Totals (N records)" into the first non-empty
        # column: either Part Number itself, or Description when Part Number is
        # blank. A real line item has a part number AND (description or qty).
        if TOTALS_RE.match(non_empty[0].strip()) and (
                not row.get(part_header, "").strip()
                or (not row.get(desc_header, "").strip() and not row.get(qty_header, "").strip())):
            skipped.append(SkippedRow(data_idx, line_no, "totals", _row_preview(cells)))
            continue
        rows.append(row)

    return ParseResult(
        encoding=encoding, had_bom=had_bom, delimiter=delimiter,
        header_row_index=header_idx, original_columns=headers, rows=rows,
        skipped=skipped, warnings=warnings, mapping=mapping,
        aliases_used=aliases_used, group_column=group_column,
        total_price_column=total_price_column,
    )


# --- Transform ---------------------------------------------------------------


def transform(parse: ParseResult, options: Options) -> ConvertResult:
    """Rename/reorder/add columns per the Tigerpaw spec, then clean every cell."""
    mapping_out: dict[str, str] = {src: COLUMN_MAPPING[c] for src, c in parse.mapping.items()}
    consumed: set[str] = set(mapping_out)
    dropped: list[str] = []
    if parse.total_price_column:
        dropped.append(parse.total_price_column)
        consumed.add(parse.total_price_column)
    if options.group_as_phase and parse.group_column:
        mapping_out[parse.group_column] = "Project Phase"
        consumed.add(parse.group_column)

    # A source column literally named like a Tigerpaw target (e.g. "List
    # Price", "Vendor") feeds that column instead of being duplicated as an
    # extra — this matches v1, where pandas kept the existing column.
    target_by_norm = {t.lower(): t for t in NEW_COLUMNS}
    for h in parse.original_columns:
        if h in consumed:
            continue
        t = target_by_norm.get(_norm_header(h))
        if t and t not in mapping_out.values():
            mapping_out[h] = t
            consumed.add(h)

    extras = [h for h in parse.original_columns if h not in consumed] if options.keep_extras else []
    ordered = list(DESIRED_ORDER)
    columns = ordered + extras
    added = [c for c in NEW_COLUMNS if c not in mapping_out.values()]

    raw_rows: list[dict[str, str]] = []
    for row in parse.rows:
        out = {c: "" for c in columns}
        for src, target in mapping_out.items():
            out[target] = row.get(src, "")
        for h in extras:
            out[h] = row.get(h, "")
        raw_rows.append(out)

    if options.ascii_only:
        # Extra header names come from the source file and may carry stray
        # Unicode too; clean them (unlogged — they're not data).
        cleaned_cols = []
        for c in columns:
            cleaned, _ = clean_cell(c, "", options)
            cleaned_cols.append(cleaned or c)
        if cleaned_cols != columns:
            raw_rows = [{n: r[o] for o, n in zip(columns, cleaned_cols)} for r in raw_rows]
            extras = [cleaned_cols[columns.index(e)] for e in extras]
            columns = cleaned_cols

    rows, changes, warnings = clean_rows(columns, raw_rows, options)
    return ConvertResult(
        parse=parse, options=options, transformed_columns=columns,
        transformed_rows=rows, changes=changes,
        warnings=list(parse.warnings) + warnings, mapping_out=mapping_out,
        added_columns=added, dropped_columns=dropped,
    )


def convert_bytes(data: bytes, options: Options | None = None) -> ConvertResult:
    """Full pipeline: bytes in → :class:`ConvertResult` (call ``.to_csv()`` for bytes)."""
    return transform(parse_salesforce_csv(data), options or Options())


# --- Output ------------------------------------------------------------------


def build_csv(columns: list[str], rows: list[dict], options: Options | None = None) -> bytes:
    """Serialize rows to CSV bytes: CRLF, minimal or full quoting, optional BOM.

    With ``ascii_only`` the text is pure ASCII so the bytes read identically
    as UTF-8, Windows-1252 or ASCII — the BOM is the only non-ASCII byte and
    is kept by default because v1's BOM'd header is what Tigerpaw has been
    importing successfully.
    """
    options = options or Options()
    buf = io.StringIO()
    writer = csv.writer(
        buf,
        lineterminator="\r\n",
        quoting=csv.QUOTE_ALL if options.quote_all else csv.QUOTE_MINIMAL,
    )
    writer.writerow(columns)
    for row in rows:
        writer.writerow(["" if row.get(c) is None else str(row.get(c)) for c in columns])
    text = buf.getvalue()
    return text.encode("utf-8-sig" if options.bom else "utf-8")


def preview_payload(result: ConvertResult, filename: str, limit: int) -> dict:
    """Shape a :class:`ConvertResult` into the ``/api/preview`` JSON contract."""
    parse = result.parse
    changes = result.changes
    warnings = result.warnings
    return {
        "filename": filename,
        "rowCount": len(result.transformed_rows),
        "previewLimit": limit,
        "truncated": len(result.transformed_rows) > limit,
        "encoding": parse.encoding,
        "hadBom": parse.had_bom,
        "delimiter": parse.delimiter,
        "headerRowIndex": parse.header_row_index,
        "originalColumns": parse.original_columns,
        "transformedColumns": result.transformed_columns,
        "originalPreview": parse.rows[:limit],
        "transformedPreview": result.transformed_rows[:limit],
        "mapping": result.mapping_out,
        "aliasesUsed": parse.aliases_used,
        "addedColumns": result.added_columns,
        "droppedColumns": result.dropped_columns,
        "skippedRows": [s.to_dict() for s in parse.skipped],
        "changes": [c.to_dict() for c in changes[:MAX_LOG_ENTRIES]],
        "warnings": [w.to_dict() for w in warnings[:MAX_LOG_ENTRIES]],
        "changesTruncated": len(changes) > MAX_LOG_ENTRIES,
        "warningsTruncated": len(warnings) > MAX_LOG_ENTRIES,
        "options": result.options.to_dict(),
    }
