"""Route / integration tests for SalesforceToTigerpaw (Flask layer).

The engine itself is covered in test_converter.py; these tests check the
HTTP contract: shapes, status codes, headers, options plumbing, telemetry.
"""

from __future__ import annotations

import csv
import io
import json
import os
import sys
import tempfile
import unittest
import zipfile

# Point the app at a fresh on-disk DB before import so tests don't share state
# with whatever ran last on this machine.
_TEST_DATA_DIR = tempfile.mkdtemp(prefix="forge-test-")
os.environ["FORGE_DATA_DIR"] = _TEST_DATA_DIR
os.environ.setdefault("ADMIN_PASSWORD", "testpw")

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from SalesforceToTigerpaw import (  # noqa: E402
    COLUMN_MAPPING,
    DESIRED_ORDER,
    NEW_COLUMNS,
    PREVIEW_ROWS,
    VERSION,
    app,
)

HEADER = ["Product Code", "Description", "Quantity", "Net Unit Price", "Unit Cost", "Total Price", "Extra"]


def _sample_rows(rows=2):
    return [
        [f"SKU-{i}", f"Widget {i}", f"{i + 1}.00", f"{10.0 * (i + 1):.2f}", f"{5.0 * (i + 1):.2f}",
         f"{10.0 * (i + 1) * (i + 1):.2f}", "x"]
        for i in range(rows)
    ]


def _sample_csv_bytes(rows=2, extra_lines=()) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf, quoting=csv.QUOTE_ALL, lineterminator="\n")
    w.writerow(HEADER)
    for r in _sample_rows(rows):
        w.writerow(r)
    return (buf.getvalue() + "".join(l + "\n" for l in extra_lines)).encode("utf-8")


def _upload(client, path, data, name="in.csv", fields=None, headers=None):
    form = {"file": (io.BytesIO(data), name)}
    form.update(fields or {})
    return client.post(path, data=form, content_type="multipart/form-data", headers=headers or {})


class ConvertRouteTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_rejects_request_without_file_part(self):
        r = self.client.post("/api/convert", data={})
        self.assertEqual(r.status_code, 400)
        self.assertIn("error", r.get_json())

    def test_rejects_non_csv_extension(self):
        r = _upload(self.client, "/api/convert", b"hi", name="not.txt")
        self.assertEqual(r.status_code, 400)

    def test_rejects_empty_csv(self):
        r = _upload(self.client, "/api/convert", b"", name="empty.csv")
        self.assertEqual(r.status_code, 400)

    def test_rejects_missing_required_columns(self):
        r = _upload(self.client, "/api/convert", b"Foo,Bar\n1,2\n", name="bad.csv")
        self.assertEqual(r.status_code, 400)
        msg = r.get_json()["error"]
        self.assertIn("Missing expected columns", msg)
        self.assertIn("Product Code", msg)

    def test_converts_valid_csv(self):
        r = _upload(self.client, "/api/convert", _sample_csv_bytes())
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.mimetype, "text/csv")
        self.assertIn('filename="in_converted.csv"', r.headers["Content-Disposition"])
        self.assertTrue(r.data.startswith(b"\xef\xbb\xbf"))
        rows = list(csv.reader(io.StringIO(r.data.decode("utf-8-sig"))))
        self.assertEqual(rows[0][: len(DESIRED_ORDER)], DESIRED_ORDER)
        self.assertEqual(rows[0][-1], "Extra")
        self.assertEqual(rows[1][:5], ["SKU-0", "Widget 0", "1.00", "10.00", "5.00"])
        self.assertEqual(rows[1][5], "")  # Total Price emptied

    def test_summary_header(self):
        data = _sample_csv_bytes(rows=3, extra_lines=["", '"Copyright (c) salesforce.com"'])
        r = _upload(self.client, "/api/convert", data)
        self.assertEqual(r.status_code, 200)
        summary = json.loads(r.headers["X-Convert-Summary"])
        self.assertEqual(summary["rows"], 3)
        self.assertEqual(summary["skipped"], 2)
        self.assertEqual(summary["encoding"], "utf-8")

    def test_options_from_form_fields(self):
        r = _upload(self.client, "/api/convert", _sample_csv_bytes(),
                    fields={"bom": "false", "quoteAll": "true", "keepExtras": "false"})
        self.assertEqual(r.status_code, 200)
        self.assertFalse(r.data.startswith(b"\xef\xbb\xbf"))
        first = r.data.decode().splitlines()[0]
        self.assertTrue(first.startswith('"Part Number","Description"'))
        self.assertNotIn("Extra", first)

    def test_cp1252_input_no_longer_500s(self):
        raw = (b'"Product Code","Description","Quantity","Net Unit Price","Unit Cost"\n'
               b'"A1","Brandon\x92s bracket","1.00","2.00","1.00"\n')
        r = _upload(self.client, "/api/convert", raw)
        self.assertEqual(r.status_code, 200)
        self.assertIn(b"Brandon's bracket", r.data)


class PreviewRouteTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_returns_preview_json(self):
        data = _sample_csv_bytes(rows=3, extra_lines=["", '"Generated By: Someone"'])
        r = _upload(self.client, "/api/preview", data)
        self.assertEqual(r.status_code, 200)
        body = r.get_json()
        self.assertEqual(body["rowCount"], 3)
        self.assertEqual(body["previewLimit"], PREVIEW_ROWS)
        self.assertFalse(body["truncated"])
        self.assertEqual(body["encoding"], "utf-8")
        self.assertFalse(body["hadBom"])
        self.assertEqual(body["delimiter"], ",")
        self.assertEqual(body["headerRowIndex"], 0)
        self.assertIn("Product Code", body["originalColumns"])
        self.assertIn("Part Number", body["transformedColumns"])
        self.assertEqual(len(body["originalPreview"]), 3)
        self.assertEqual(len(body["transformedPreview"]), 3)
        self.assertEqual(body["mapping"], COLUMN_MAPPING)
        self.assertEqual(body["aliasesUsed"], {})
        self.assertIn("Total Price", body["droppedColumns"])
        self.assertEqual(sorted(body["addedColumns"]), sorted(NEW_COLUMNS))
        self.assertEqual([x["reason"] for x in body["skippedRows"]], ["blank", "footer"])
        self.assertEqual(body["changes"], [])
        self.assertEqual(body["warnings"], [])
        self.assertFalse(body["changesTruncated"])
        self.assertEqual(body["options"]["asciiOnly"], True)
        # Values are strings, never numbers: "1.00" survives.
        self.assertEqual(body["transformedPreview"][0]["Quantity"], "1.00")
        self.assertEqual(body["originalPreview"][0]["Quantity"], "1.00")

    def test_preview_reports_changes_and_aliases(self):
        buf = io.StringIO()
        w = csv.writer(buf, quoting=csv.QUOTE_ALL, lineterminator="\n")
        w.writerow(["Part Number", "Description", "Qty", "Net Unit Price", "Unit Cost"])
        w.writerow(["A", "Verkada\u2019s cam", "$1,000", "2", "3"])
        r = _upload(self.client, "/api/preview", buf.getvalue().encode("utf-8"))
        body = r.get_json()
        self.assertEqual(body["aliasesUsed"], {"Part Number": "Product Code", "Qty": "Quantity"})
        self.assertEqual(body["mapping"]["Qty"], "Quantity")
        kinds = {c["column"]: c["kind"] for c in body["changes"]}
        self.assertEqual(kinds, {"Description": "punctuation", "Quantity": "number"})
        change = next(c for c in body["changes"] if c["column"] == "Description")
        self.assertEqual(change["from"], "Verkada\u2019s cam")
        self.assertEqual(change["to"], "Verkada's cam")
        self.assertEqual(change["row"], 0)

    def test_preview_rejects_missing_columns(self):
        r = _upload(self.client, "/api/preview", b"Foo,Bar\n1,2\n")
        self.assertEqual(r.status_code, 400)


class ConvertEditedRouteTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_rejects_missing_columns(self):
        r = self.client.post("/api/convert-edited", json={"rows": []})
        self.assertEqual(r.status_code, 400)

    def test_rejects_non_list_rows(self):
        r = self.client.post(
            "/api/convert-edited", json={"columns": ["A"], "rows": "nope"}
        )
        self.assertEqual(r.status_code, 400)

    def test_serializes_edited_rows_preserving_order(self):
        body = {
            "filename": "edited.csv",
            "columns": ["Part Number", "Description", "Vendor"],
            "rows": [
                {"Part Number": "A1", "Description": "Widget", "Vendor": "ACME"},
                {"Part Number": "B2", "Description": "Gadget", "Vendor": None},
            ],
        }
        r = self.client.post("/api/convert-edited", json=body)
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.mimetype, "text/csv")
        self.assertIn('filename="edited.csv"', r.headers["Content-Disposition"])
        lines = r.data.decode("utf-8-sig").splitlines()
        self.assertEqual(lines[0], "Part Number,Description,Vendor")
        self.assertEqual(lines[1], "A1,Widget,ACME")
        self.assertEqual(lines[2], "B2,Gadget,")
        self.assertIn("X-Convert-Summary", r.headers)

    def test_edited_cells_are_cleaned(self):
        body = {
            "filename": "edited.csv",
            "columns": ["Part Number", "Description", "Quantity"],
            "rows": [{"Part Number": "A1", "Description": "pasted \u201cquote\u201d\nnext", "Quantity": "$3"}],
        }
        r = self.client.post("/api/convert-edited", json=body)
        self.assertEqual(r.status_code, 200)
        lines = r.data.decode("utf-8-sig").splitlines()
        self.assertEqual(lines[1], 'A1,"pasted ""quote"" next",3')
        summary = json.loads(r.headers["X-Convert-Summary"])
        self.assertEqual(summary["changes"], 2)

    def test_edited_options_nested(self):
        body = {
            "filename": "edited.csv",
            "columns": ["Part Number"],
            "rows": [{"Part Number": "A1"}],
            "options": {"bom": False, "quoteAll": True},
        }
        r = self.client.post("/api/convert-edited", json=body)
        self.assertEqual(r.data, b'"Part Number"\r\n"A1"\r\n')

    def test_rejects_non_dict_rows(self):
        r = self.client.post("/api/convert-edited", json={"columns": ["A"], "rows": ["nope"]})
        self.assertEqual(r.status_code, 400)


class ConvertBatchRouteTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_rejects_empty_batch(self):
        r = self.client.post("/api/convert-batch", data={})
        self.assertEqual(r.status_code, 400)

    def test_converts_multiple_files_into_zip(self):
        zf = zipfile

        r = self.client.post(
            "/api/convert-batch",
            data={
                "files": [
                    (io.BytesIO(_sample_csv_bytes(rows=2)), "a.csv"),
                    (io.BytesIO(_sample_csv_bytes(rows=3)), "b.csv"),
                ],
            },
            content_type="multipart/form-data",
        )
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.mimetype, "application/zip")
        archive = zf.ZipFile(io.BytesIO(r.data))
        names = archive.namelist()
        self.assertIn("a_converted.csv", names)
        self.assertIn("b_converted.csv", names)
        self.assertNotIn("_errors.txt", names)
        self.assertIn("_report.txt", names)
        report = archive.read("_report.txt").decode()
        self.assertIn("[OK]    a.csv -> a_converted.csv: 2 rows", report)
        self.assertIn("[OK]    b.csv -> b_converted.csv: 3 rows", report)
        self.assertIn(VERSION, report)
        self.assertEqual(r.headers["X-Batch-Summary"], "2/2 succeeded")

    def test_partial_failure_includes_errors_file(self):
        zf = zipfile

        bad_csv = b"Foo,Bar\n1,2\n"
        r = self.client.post(
            "/api/convert-batch",
            data={
                "files": [
                    (io.BytesIO(_sample_csv_bytes()), "good.csv"),
                    (io.BytesIO(bad_csv), "bad.csv"),
                ],
            },
            content_type="multipart/form-data",
        )
        self.assertEqual(r.status_code, 200)
        archive = zf.ZipFile(io.BytesIO(r.data))
        names = archive.namelist()
        self.assertIn("good_converted.csv", names)
        self.assertIn("_errors.txt", names)
        self.assertIn("bad.csv", archive.read("_errors.txt").decode())
        self.assertIn("[ERROR] bad.csv", archive.read("_report.txt").decode())


class SpaRouteTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_root_returns_something(self):
        # Either serves the built SPA or the "frontend not built" JSON — both fine.
        r = self.client.get("/")
        self.assertIn(r.status_code, (200, 503))

    def test_health(self):
        r = self.client.get("/api/health")
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.get_json(), {"status": "ok", "version": VERSION})

    def test_api_http_errors_are_json(self):
        # The SPA catch-all answers GET for any path, so a POST to an unknown
        # /api/ path is a 405; what matters is that it comes back as JSON.
        r = self.client.post("/api/does-not-exist")
        self.assertEqual(r.status_code, 405)
        self.assertIn("error", r.get_json())

    def test_traversal_attempt_falls_back_to_spa_or_503(self):
        # A path that tries to escape the build dir must not leak /etc/passwd
        # or any other file. The expected behavior is the SPA fallback (200
        # index.html) or 503 if the frontend isn't built — never a 200 with
        # the traversal target's contents.
        r = self.client.get("/../../etc/passwd")
        self.assertIn(r.status_code, (200, 404, 503))
        self.assertNotIn(b"root:", r.data)

    def test_encoded_traversal_attempt_is_safe(self):
        r = self.client.get("/%2e%2e/%2e%2e/etc/passwd")
        self.assertIn(r.status_code, (200, 404, 503))
        self.assertNotIn(b"root:", r.data)


class UploadLimitTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_oversize_upload_returns_413(self):
        # MAX_CONTENT_LENGTH is 10 MB; 11 MB of junk should be rejected before
        # we even parse the CSV.
        big = io.BytesIO(b"a,b,c\n" + b"0," * (11 * 1024 * 1024 // 2))
        r = self.client.post(
            "/api/convert",
            data={"file": (big, "big.csv")},
            content_type="multipart/form-data",
        )
        self.assertEqual(r.status_code, 413)
        self.assertIn("error", r.get_json())


class IdentifyAndAdminTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def _login(self):
        r = self.client.post("/admin/login", data={"password": "testpw"})
        self.assertIn(r.status_code, (302, 303))

    def test_identify_creates_user_and_event(self):
        r = self.client.post(
            "/api/identify",
            json={"name": "Brandon T.", "firstTime": True},
            headers={"User-Agent": "Mozilla/5.0 (Macintosh) Chrome/120"},
        )
        self.assertEqual(r.status_code, 200)
        body = r.get_json()
        self.assertEqual(body["name"], "Brandon T.")
        self.assertTrue(body["ok"])

    def test_identify_rejects_empty_name(self):
        r = self.client.post("/api/identify", json={"name": "   "})
        self.assertEqual(r.status_code, 400)

    def test_identify_rejects_guest(self):
        r = self.client.post("/api/identify", json={"name": "guest"})
        self.assertEqual(r.status_code, 400)

    def test_admin_routes_require_login(self):
        r = self.client.get("/admin/api/stats")
        self.assertEqual(r.status_code, 401)
        r2 = self.client.get("/admin")
        self.assertEqual(r2.status_code, 302)  # redirect to login

    def test_admin_login_wrong_password(self):
        r = self.client.post("/admin/login", data={"password": "nope"})
        self.assertEqual(r.status_code, 401)

    def test_admin_flow_stats_and_events(self):
        # Perform a convert so there's something to see.
        csv_bytes = _sample_csv_bytes(rows=2)
        self.client.post(
            "/api/convert",
            data={"file": (io.BytesIO(csv_bytes), "hit.csv")},
            content_type="multipart/form-data",
            headers={"X-User-Name": "Tester", "User-Agent": "Mozilla/5.0 Chrome/120"},
        )
        self._login()
        stats = self.client.get("/admin/api/stats").get_json()
        self.assertGreaterEqual(stats["totalEvents"], 1)
        self.assertGreaterEqual(stats["totalUsers"], 1)

        events = self.client.get("/admin/api/events?limit=5").get_json()
        self.assertTrue(any(e["type"] == "convert" for e in events["events"]))

        users = self.client.get("/admin/api/users").get_json()
        tester = next((u for u in users["users"] if u["name"] == "Tester"), None)
        self.assertIsNotNone(tester)
        self.assertGreaterEqual(tester["eventCount"], 1)

        detail = self.client.get(f"/admin/api/user/{tester['id']}").get_json()
        self.assertEqual(detail["user"]["name"], "Tester")
        self.assertTrue(len(detail["events"]) >= 1)

    def test_reset_wipes_telemetry(self):
        self._login()
        # Generate an event
        self.client.post(
            "/api/convert",
            data={"file": (io.BytesIO(_sample_csv_bytes()), "hit.csv")},
            content_type="multipart/form-data",
            headers={"X-User-Name": "ToDelete"},
        )
        r = self.client.post("/admin/api/reset")
        self.assertEqual(r.status_code, 200)
        stats = self.client.get("/admin/api/stats").get_json()
        self.assertEqual(stats["totalUsers"], 0)
        self.assertEqual(stats["totalEvents"], 0)

    def test_reset_wipes_notes_and_feedback_and_bumps_token(self):
        # Seed across every persistence surface so we can verify each is
        # wiped — this is the bug the user reported: reset was only hitting
        # users + events, leaving notes, feedback, and ip_geo behind.
        self.client.post(
            "/api/notes", json={"text": "pre-reset note"},
            headers={"X-User-Name": "Seed"},
        )
        self.client.post(
            "/api/feedback", json={"kind": "suggestion", "text": "pre-reset idea"},
            headers={"X-User-Name": "Seed"},
        )
        # Capture the resetAt baseline before wiping.
        before = self.client.get("/api/public-stats").get_json().get("resetAt", "")

        self._login()
        r = self.client.post("/admin/api/reset")
        self.assertEqual(r.status_code, 200)

        notes = self.client.get("/api/notes").get_json()["notes"]
        self.assertEqual(notes, [])

        fb = self.client.get("/admin/api/feedback?status=all").get_json()
        self.assertEqual(fb["items"], [])
        self.assertEqual(fb["openCount"], 0)

        after = self.client.get("/api/public-stats").get_json().get("resetAt", "")
        self.assertNotEqual(before, after)
        self.assertGreater(after, before)


class PublicStatsAndNotesTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_public_stats_endpoint_shape(self):
        r = self.client.get("/api/public-stats")
        self.assertEqual(r.status_code, 200)
        body = r.get_json()
        for k in ("totalJobs", "jobsToday", "activeUsers", "topAllTime", "resetAt"):
            self.assertIn(k, body)
        self.assertIsInstance(body["topAllTime"], list)
        # Podium is capped at 3 — backend enforces this regardless of how
        # many distinct users there are.
        self.assertLessEqual(len(body["topAllTime"]), 3)

    def test_notes_roundtrip_requires_name(self):
        # Without X-User-Name the backend falls back to Guest which is rejected.
        r = self.client.post("/api/notes", json={"text": "hi"})
        self.assertEqual(r.status_code, 400)

        r = self.client.post(
            "/api/notes",
            json={"text": "crushing it today!"},
            headers={"X-User-Name": "Noter"},
        )
        self.assertEqual(r.status_code, 200)
        body = r.get_json()
        self.assertEqual(body["user"], "Noter")
        self.assertEqual(body["text"], "crushing it today!")

        r = self.client.get("/api/notes?limit=5")
        self.assertEqual(r.status_code, 200)
        notes = r.get_json()["notes"]
        self.assertTrue(any(n["text"] == "crushing it today!" for n in notes))

    def test_notes_rejects_empty_and_too_long(self):
        hdr = {"X-User-Name": "Noter"}
        r1 = self.client.post("/api/notes", json={"text": "   "}, headers=hdr)
        self.assertEqual(r1.status_code, 400)
        r2 = self.client.post("/api/notes", json={"text": "x" * 300}, headers=hdr)
        self.assertEqual(r2.status_code, 400)


class FeedbackTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_feedback_requires_name(self):
        r = self.client.post("/api/feedback", json={"kind": "suggestion", "text": "hi"})
        self.assertEqual(r.status_code, 400)

    def test_feedback_rejects_bad_kind(self):
        r = self.client.post(
            "/api/feedback",
            json={"kind": "rant", "text": "hi"},
            headers={"X-User-Name": "Reporter"},
        )
        self.assertEqual(r.status_code, 400)

    def test_feedback_roundtrip_and_admin_actions(self):
        # Submit
        r = self.client.post(
            "/api/feedback",
            json={"kind": "issue", "text": "Upload fails on Safari"},
            headers={"X-User-Name": "Reporter"},
        )
        self.assertEqual(r.status_code, 200)
        fid = r.get_json()["id"]

        # Admin login, list, resolve, reopen, delete.
        self.client.post("/admin/login", data={"password": "testpw"})

        listed = self.client.get("/admin/api/feedback?status=open").get_json()
        self.assertTrue(any(i["id"] == fid for i in listed["items"]))
        self.assertGreaterEqual(listed["openCount"], 1)

        r2 = self.client.post(f"/admin/api/feedback/{fid}/resolve")
        self.assertEqual(r2.status_code, 200)

        resolved = self.client.get("/admin/api/feedback?status=resolved").get_json()
        self.assertTrue(any(i["id"] == fid and i["status"] == "resolved" for i in resolved["items"]))

        r3 = self.client.post(f"/admin/api/feedback/{fid}/reopen")
        self.assertEqual(r3.status_code, 200)

        r4 = self.client.delete(f"/admin/api/feedback/{fid}")
        self.assertEqual(r4.status_code, 200)
        final = self.client.get("/admin/api/feedback?status=all").get_json()
        self.assertFalse(any(i["id"] == fid for i in final["items"]))


class AdminExportAndDeleteTests(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()
        self.client.post("/admin/login", data={"password": "testpw"})

    def test_export_returns_csv(self):
        # Seed an event
        self.client.post(
            "/api/convert",
            data={"file": (io.BytesIO(_sample_csv_bytes()), "x.csv")},
            content_type="multipart/form-data",
            headers={"X-User-Name": "Exporter"},
        )
        r = self.client.get("/admin/api/export")
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.mimetype, "text/csv")
        first_line = r.data.splitlines()[0].decode("utf-8-sig")
        self.assertIn("user_name", first_line)
        self.assertIn("event_type", first_line)

    def test_delete_user_removes_their_events(self):
        self.client.post(
            "/api/convert",
            data={"file": (io.BytesIO(_sample_csv_bytes()), "x.csv")},
            content_type="multipart/form-data",
            headers={"X-User-Name": "GoingAway"},
        )
        users = self.client.get("/admin/api/users").get_json()["users"]
        target = next((u for u in users if u["name"] == "GoingAway"), None)
        self.assertIsNotNone(target)
        r = self.client.post(f"/admin/api/user/{target['id']}/delete")
        self.assertEqual(r.status_code, 200)

        users_after = self.client.get("/admin/api/users").get_json()["users"]
        self.assertFalse(any(u["name"] == "GoingAway" for u in users_after))


if __name__ == "__main__":
    unittest.main()
